#项目启动端口
server:
  port: 8080
# 数据源配置(spring boot提供的Hikaricp)
spring:
  datasource:
    username: root
    password: GCFgcf106424
    url: jdbc:mysql://localhost:3306/family_service_platform?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置mybatis
mybatis:
  mapper-locations: classpath:com/example/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#Sql日志打印
logging:
  level:
    com:
      example:
        mapper: debug


